/*

 MINESTEPPERFIELD.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\miles\Downloads\GBTD_GBMB_release\Assets\minestepper.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __minestepperField_h_INCLUDE
#define __minestepperField_h_INCLUDE

#define minestepperFieldWidth 20
#define minestepperFieldHeight 18
#define minestepperFieldBank 0

extern const unsigned char minestepperField[];

#endif

/* End of MINESTEPPERFIELD.H */
